version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", '/usr/bin/psql -U your_user -h localhost -p 5432 -d your_database -c "select version();"']

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
      DB_PORT: 5432
      DB_SSLMODE: disable
      REFERRAL_LINK_EXP: 7d
      JWT_SECRET: your_jwt_secret
    command: ["/app/startup.sh"]
  
volumes:
  pgdata:
