version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", '/usr/bin/psql -U your_user -h localhost -p 5432 -d your_database -c "select version();"']
    networks:
      - jubelio_networks

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["/app/startup.sh"]
    networks:
      - jubelio_networks

networks:
  jubelio_networks:
    external: true
  
volumes:
  pgdata:
